#pragma once
#include "math/vec.hpp"
#include "math/mat.hpp"
#include "math/color.hpp"
#include "core/screen_buffer.hpp"
#include "core/terminal.hpp"
#include "graphics/rasterizer.hpp"
#include "graphics/graphics_types.hpp"
#include "core/renderer.hpp"
